Update npm.yml

diff --git a/.github/workflows/npm.yml b/.github/workflows/npm.yml
--- a/.github/workflows/npm.yml
+++ b/.github/workflows/npm.yml
@@ -36,5 +36,13 @@ jobs:
           echo "JFrog login successful."
         else
           echo "JFrog login failed. Response: $response"
-          exit 1
+          echo "Retrying after 25 seconds..."
+          sleep 25
+          response=$(curl -u "${{ secrets.ARTIFACTORY_USERNAME }}:${{ secrets.ARTIFACTORY_PASSWORD }}" -i "${{ secrets.ARTIFACTORY_URL }}/api/system/ping" 2>&1)
+          if echo "$response" | grep -q "HTTP/1.1 200 OK"; then
+            echo "JFrog login successful after retry."
+          else
+            echo "JFrog login failed after retry. Response: $response"
+            exit 1
+          fi
         fi
